#!/bin/bash
# Setup script for V2 Staging on Render
# This ensures EVERYTHING is configured correctly from the start

echo "🚀 ========================================="
echo "🚀 WAR ROOM V2 STAGING SETUP"
echo "🚀 ========================================="
echo ""

echo "📋 V2 Staging Configuration:"
echo "   Name: war-room-v2-staging"
echo "   Branch: aug12-working-deployment"
echo "   Build: Frontend AND Backend"
echo ""

echo "✅ Features that WILL work:"
echo "   • Slate/gray theme (not purple)"
echo "   • No verbose page headers"
echo "   • No navigation icons"
echo "   • Tab overflow prevention"
echo "   • All UI improvements"
echo ""

echo "📝 Instructions for Render Dashboard:"
echo ""
echo "1. Go to: https://dashboard.render.com/new/web"
echo ""
echo "2. Connect GitHub repo: Think-Big-Media/1.0-war-room"
echo ""
echo "3. Configure service:"
echo "   Name: war-room-v2-staging"
echo "   Runtime: Python 3"
echo "   Branch: aug12-working-deployment"
echo "   Build Command:"
echo "   pip install -r requirements.txt && cd src/frontend && npm install && npm run build"
echo ""
echo "   Start Command:"
echo "   cd src/backend && python serve_bulletproof.py"
echo ""
echo "4. Environment Variables:"
echo "   PYTHON_VERSION = 3.11"
echo "   NODE_VERSION = 20.11.1"
echo "   PORT = 10000"
echo ""
echo "5. Click 'Create Web Service'"
echo ""
echo "🎯 CRITICAL: The Build Command MUST include:"
echo "   - pip install (for backend)"
echo "   - npm install (for frontend)"
echo "   - npm run build (for frontend)"
echo ""
echo "Without ALL THREE, the UI changes won't appear!"
echo ""