#!/bin/bash
# This script contains the actual environment variables for Render deployment

cat << 'EOF' > /Users/rodericandrews/WarRoom_Development/1.0-war-room/.env.production
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}
JWT_SECRET=war-room-secure-jwt-2025-production
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
FACEBOOK_ACCESS_TOKEN=${FACEBOOK_ACCESS_TOKEN}
FACEBOOK_SANDBOX_TOKEN=${FACEBOOK_SANDBOX_TOKEN}
GOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID}
GOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET}
GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}
SENDGRID_FROM_EMAIL=Info@wethinkbig.io
SUPABASE_URL=https://ksnrafwskxaxhaczvwjs.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbnJhZndza3hheGhhY3p2d2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjc2MTQsImV4cCI6MjA2NzY0MzYxNH0.d7lM7Jp6CVxPesip1JVYPMUEkifQ39biLQNzEhNfd-w
TWILIO_PHONE_NUMBER=+18139652725
RENDER_ENV=production
NODE_ENV=production
PYTHON_ENV=production
VERSION=1.0.0
BACKEND_CORS_ORIGINS=["https://war-room-oa9t.onrender.com","http://localhost:3000","http://localhost:5173"]
RATE_LIMIT_PER_MINUTE=60
LOG_LEVEL=INFO
EOF