name: CodeRabbit Review
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CodeRabbit
        run: echo "CodeRabbit auto-triggered"